version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FLASK_PORT
    ports:
      - "${ FLASK_PORT }:${ FLASK_PORT }"
    env_file:
      - .env
    volumes:
      - ./config_files:/app/config_files

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
    ports:
      - "${ NGINX_HOST_PORT} :${ NGINX_CONTAINER_PORT }"
    environment:
      - FLASK_PORT=${ FLASK_PORT }
      - NGINX_HOST_PORT=${ NGINX_HOST_PORT }
    depends_on:
      - flask
